//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForumDev.Social
{
    public partial class Social
    {
        /// <summary>
        /// statsPanel 控制項。
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl statsPanel;

        /// <summary>
        /// lblFriendCount 控制項。
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblFriendCount;

        /// <summary>
        /// lblRoomCount 控制項。
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblRoomCount;

        /// <summary>
        /// lblMessageCount 控制項。
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMessageCount;

        /// <summary>
        /// pnlMessage 控制項。
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlMessage;

        /// <summary>
        /// lblMessage 控制項。
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMessage;

        /// <summary>
        /// hfActiveTab 控制項。
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfActiveTab;

        /// <summary>
        /// hfShowChatModal 控制項。
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfShowChatModal;

        /// <summary>
        /// pnlNotLoggedIn 控制項。
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlNotLoggedIn;

        /// <summary>
        /// pnlMainContent 控制項。
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlMainContent;

        /// <summary>
        /// lblPendingBadge 控制項。
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblPendingBadge;

        /// <summary>
        /// imgCurrentUserAvatar 控制項。
        /// </summary>
        protected global::System.Web.UI.WebControls.Image imgCurrentUserAvatar;

        /// <summary>
        /// txtNewMessage 控制項。
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtNewMessage;

        /// <summary>
        /// btnPostMessage 控制項。
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnPostMessage;

        /// <summary>
        /// rptMessages 控制項。
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptMessages;

        /// <summary>
        /// pnlNoMessages 控制項。
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlNoMessages;

        /// <summary>
        /// txtSearchUser 控制項。
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtSearchUser;

        /// <summary>
        /// btnSearchUser 控制項。
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSearchUser;

        /// <summary>
        /// pnlSearchResults 控制項。
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlSearchResults;

        /// <summary>
        /// rptSearchResults 控制項。
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptSearchResults;

        /// <summary>
        /// pnlPendingRequests 控制項。
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlPendingRequests;

        /// <summary>
        /// rptPendingRequests 控制項。
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptPendingRequests;

        /// <summary>
        /// rptFriends 控制項。
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptFriends;

        /// <summary>
        /// pnlNoFriends 控制項。
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlNoFriends;

        /// <summary>
        /// txtRoomName 控制項。
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtRoomName;

        /// <summary>
        /// txtRoomDesc 控制項。
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtRoomDesc;

        /// <summary>
        /// ddlRoomType 控制項。
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlRoomType;

        /// <summary>
        /// btnCreateRoom 控制項。
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnCreateRoom;

        /// <summary>
        /// rptChatRooms 控制項。
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptChatRooms;

        /// <summary>
        /// pnlNoRooms 控制項。
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlNoRooms;

        /// <summary>
        /// lblChatRoomName 控制項。
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblChatRoomName;

        /// <summary>
        /// rptChatMessages 控制項。
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptChatMessages;

        /// <summary>
        /// hfCurrentRoomId 控制項。
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfCurrentRoomId;

        /// <summary>
        /// txtChatMessage 控制項。
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtChatMessage;

        /// <summary>
        /// btnSendChat 控制項。
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSendChat;
    }
}
